import {
  AlertTriangle,
  AudioLines,
  BarChart3,
  Bolt,
  BookOpen,
  Captions,
  Check,
  Clock,
  Cloud,
  Download,
  FileAudio,
  FileText,
  Gift,
  Github,
  Globe,
  GraduationCap,
  Heart,
  History,
  Languages,
  Laptop,
  Link2,
  Linkedin,
  Lock,
  Mail,
  Mic,
  Monitor,
  Rocket,
  Search,
  Shield,
  Sparkles,
  Star,
  Target,
  Trash2,
  Upload,
  User,
  Users,
  Video,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Icons are content: JSON stores an `iconName` and components resolve it here, so editors
 * pick from this fixed set (the admin's icon select lists ICON_NAMES).
 */
export const ICONS = {
  alert: AlertTriangle,
  audio: AudioLines,
  chart: BarChart3,
  bolt: Bolt,
  book: BookOpen,
  captions: Captions,
  check: Check,
  clock: Clock,
  cloud: Cloud,
  download: Download,
  "file-audio": FileAudio,
  "file-text": FileText,
  gift: Gift,
  github: Github,
  globe: Globe,
  graduation: GraduationCap,
  heart: Heart,
  history: History,
  languages: Languages,
  laptop: Laptop,
  link: Link2,
  linkedin: Linkedin,
  lock: Lock,
  mail: Mail,
  mic: Mic,
  monitor: Monitor,
  rocket: Rocket,
  search: Search,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  video: Video,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
export const ICON_NAMES = Object.keys(ICONS) as IconName[];

export function resolveIcon(name: string | undefined | null): LucideIcon {
  return ICONS[(name ?? "") as IconName] ?? Sparkles;
}
